
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://narendranss.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: "UA-104070503-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Narendran Solai Sridharan"
title: "Narendran Solai Sridharan"
description: "Blog and website of Narendran Solai Sridharan, blogging mainly for tech. Opinions expressed are mine."
keywords: "Naren, naren, solai, Solai, Narendran, narendran"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg2.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "League of Heroes create an Agile Team, Everyone in the team are Heroes"
  - text: "Bump away from Consumer Mindset"
  - text: "The Only disabiliity in life is Bad Attitude"

me-img: "https://github.com/narendranss.png?size=500"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "narendranss-github-io"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/softwareag.jpg"
    date: "Nov 2015 - Today"
    description: "Working at Software AG"
  - image: "/img/timeline/baracktocat.jpg"
    date: "Nov 2009 - Nov 2015"
    description: "Worked at IGATE Global Solutions"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "narendran.ss@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Narendran is an awesome person. He lives in Cheanai, where he works on software engineering projects. In his spare time, Narendran likes to write blogs."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/narendran.solaisridharan"
  - title: "twitter"
    url: "https://twitter.com/narendran_ss"
  - title: "github"
    url: "https://github.com/narendranss"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1CxHFgA6XTf5bJgJCNHccDmrNTjUwUmH7K"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: narendranss
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
